# Generated by Django 4.0.2 on 2022-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_people', models.IntegerField(blank=True, default=1, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('place_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_passport', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
