# Generated by Django 4.0.2 on 2022-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_for_payme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
